### ISSUE TITLE
Add examples of using img, inline background image, and css background image so i can copy the format throughout the app

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/air-a11y#16]

**Comment by fobabett** [comment]
**Inline BG Images**
added a util that should make it easier to add inline bg images.

at the top of the file add:
```
import { setBGImg } from '../path/to/utils.js'
```

usage:
```
<div style={setBGImg('https://placehold.it/100')}></div>
```

**img**
works as usual. Just make sure to prepend the `/`:
```
<img src="https://placehold.it/100"/>
```

**css**
should work as usual. `src/App.scss` is imported in `App.js` so any style changes there should affect the entire application.
