### ISSUE TITLE
[8] Search Results

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/air-a11y#2]
<img width="1083" alt="Screen Shot 2020-02-22 at 12 46 26 PM" src="https://user-images.githubusercontent.com/1865400/75099606-63fa3580-5578-11ea-9765-948ea8ad568c.png">

![image](https://user-images.githubusercontent.com/1865400/75099767-58a80980-557a-11ea-89cc-0f5aec3e302e.png)

- [x] highlight random search results
- [ ] thing in bottom right opens, and you can turn on/off Air A11y

**Comment by theRemix** [comment]
gonna do round trip not one way, cause that's the data we get
