### ISSUE TITLE
When a checkbox is checked, can you add class `fancy-checkbox-checked` to the predecesor element `fancy-checkbox`?

### ISSUE THREAD

**Issue by kellishouts** [AirshipCMS/air-a11y#20]
When a checkbox is checked, can you add class `fancy-checkbox-checked` to the predecesor element `fancy-checkbox`?

I built the element weird (though too tired to fix), so need a class on it, so i can make an active state for the whole element.

**Comment by theRemix** [comment]
this was only found in Seating page
